### PR TITLE
fix(hidden-class): The hidden-class now includes a !important flag, t…

### PR DESCRIPTION
**Pull request by dploeger**
…o actually hide elements and not be overridden. Relates to https://github.com/hypeJunction/hypeLists/issues/34

### CODE REVIEW

**Comment by dploeger** [comment]
Ah, damn. I just noticed, that this blanks out the entity menus, because they alway have the hidden class set (whyever...) Gonna check that out.

**Comment by dploeger** [comment]
Found it and corrected .hidden-class handling in the popup menu.

**Comment by hypeJunction** [comment]
Added you as a collaborator. Feel free to merge.
Also note that there is an scss branch, which I think I was doing the work on most recently.

**Comment by dploeger** [comment]
Great. Thanks, pal!

**Comment by dploeger** [comment]
I check out the differences with the sccs branch first.

**Comment by dploeger** [comment]
Ah damn, Master and scss differ a lot now. I'll try to untangle them. I think, I'll recreate this pull request then.

**Comment by hypeJunction** [comment]
Don't spend too much time on it. I I'll get to it eventually.

**Comment by dploeger** [comment]
Thanks. I saw, that you already incorporated this in 1.4.0. I'll close this now.

**Comment by dploeger** [comment]
Ah, but the important flag on the hidden-class was somehow lost after commit #ea8f427. However, I will wait until you incorporated the scss branch before reimplemnting it.

**Pull request closed without merging**
